const path = require('path');

const EXCLUDED_PATTERNS = [
  /[/\\]node_modules[/\\]/,
  /[/\\]dist[/\\]/,
  /[/\\]\.git[/\\]/,
  /\.min\.(js|css)$/,
  /\.map$/,
  /\.d\.ts$/,
  /(^|[/\\])package-lock\.json$/,
  /(^|[/\\])yarn\.lock$/,
  /(^|[/\\])pnpm-lock\.yaml$/,
];

const GENERATED_MARKERS = [
  'DO NOT EDIT',
  'This file is auto-generated',
  'Code generated by',
  '@generated',
  'AUTO-GENERATED',
];

function isProbablyBinary(content) {
  return content.includes('\u0000');
}

function shouldExclude(filePath, content) {
  const normalizedPath = filePath.split(path.sep).join('/');

  for (const pattern of EXCLUDED_PATTERNS) {
    if (pattern.test(normalizedPath)) {
      return 'Dependency, build output, lockfile, or generated artifact.';
    }
  }

  if (isProbablyBinary(content)) {
    return 'Binary-like file.';
  }

  const firstLines = content.slice(0, 1000);
  for (const marker of GENERATED_MARKERS) {
    if (firstLines.includes(marker)) {
      return 'Auto-generated file marker detected.';
    }
  }

  const lines = content.split('\n');
  if (lines.length < 5 && content.length > 5000) {
    return 'Minified file.';
  }

  return null;
}

module.exports = {
  shouldExclude,
};
